Punishments:
  broadcast_on_punishment: false
  report_reasons: Hacking, Offensive Comments, Bad Sportsmanship, Mechanism Abuse, Chat Spam, Ruining Gameplay, Threats, Advertise, Filter Bypass, Suicide Encouragement, Hackusation, Stalking
  enable_raw_ban_commands: false
  enable_raw_kick_command: true
  enable_raw_report_command: true
  enable_raw_spectate_command: true
  Commands:
    "1": spartan {player} if {tps} > 18.0 do spartan kick {player} {detections}
    "2": ""
    "3": ""
    "4": ""
    "5": ""
    "6": ""
    "7": ""
    "8": ""
    "9": ""
    "10": ""
Logs:
  log_file: true
  log_console: true
Notifications:
  enable_notifications_on_login: true
  awareness_notifications: true
  message_clickable_command: /teleport {player}
Chat:
  message_cooldown: 0
  command_cooldown: 0
  prevent_same_message: false
  blocked_words: blockedWord1, blockedWord2
  blocked_commands: blockedCommand1, blockedCommand2
  staff_chat_character: "@"
Protections:
  reconnect_cooldown: 1
  use_tps_protection: true
  max_supported_player_latency: 500
  use_teleport_protection: false
  avoid_self_bow_damage: true
  player_limit_per_ip: 0
  interactions_per_tick: 10
  disallowed_building: true
Important:
  op_bypass: true
  enable_permissions: true
  violations_reset_seconds: 60
  violations_reset_on_kick: false
  modify_server_configuration: false
  refresh_inventory_menu: true
  enable_developer_api: true
  show_ecosystem: true
  bedrock_player_prefix: "*"
  inventory_menu_empty_heads: true
Cloud:
  server_name: specify server name
  synchronise_files: true
Detections:
  ground_teleport_on_detection: true
  fall_damage_on_teleport: true
  allow_cancelled_hit_checking: false
  update_blocks_upon_violation: false
Performance:
  enable_false_positive_detection: true
  use_vanilla_ground_method: false
  maximum_checked_players_at_once: 100
Discord:
  webhook_hex_color: 4caf50
  checks_webhook_url: ""
  punishments_webhook_url: ""
  reports_webhook_url: ""
  communication_webhook_url: ""
